version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://${DB_POSTGRES_USER}:${DB_POSTGRES_PASSWORD}@postgres:5432/${DB_POSTGRES_DB_NAME}?sslmode=disable",
        "up"
      ]
volumes:
  pg_data: